### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by odik91** [riskihajar/terbilang#14]
### What happened?

error when install package 
syntax error, unexpected identifier "DistanceDate"

  at D:\laravel\sitoki\vendor\riskihajar\terbilang\src\Enums\DistanceDate.php:7
      3▕ namespace Riskihajar\Terbilang\Enums;
      4▕
      5▕ use Illuminate\Support\Facades\Lang;
      6▕
  ➜   7▕ enum DistanceDate: string
      8▕ {
      9▕     case Day = 'Day';
     10▕     case Month = 'Month';
     11▕     case Hour = 'Hour';
composer says DistanceDate not found

### How to reproduce the bug

error after run composer require riskihajar/terbilang:^2.0
or update composer with riskihajar/terbilang package included

### Package Version

2.0.2

### PHP Version

9.2

### Laravel Version

9

### Which operating systems does with happen with?

win 10 64

### Notes

how to fix this

**Comment by riskihajar** [comment]
halo, mas @odik91 apakah masih terjadi bug?
jika tidak ada mau saya close issue nya.

**Comment by odik91** [comment]
udah, kemaren kasus muncul ketika nerusin projek orang tanpa ngecek versi phpnya
