### ISSUE TITLE
[Bug]: Method  cannot be called statically

### ISSUE THREAD

**Issue by priana13** [riskihajar/terbilang#20]
### What happened?

Non-static method Riskihajar\Terbilang\Terbilang::make() cannot be called statically

### How to reproduce the bug

Saya panggil nya  menggunakan

$terbilang =  new Terbilang();
$text = $terbilang->make(300000);

atau ada cara yang lebih tepat?

Terimakasih.

### Package Version

2

### PHP Version

8.1

### Laravel Version

10

### Which operating systems does with happen with?

Linux

**Comment by riskihajar** [comment]
halo @priana13 maaf baru respon.

untuk memanggil static, gunakan facades. contoh :
```php
Riskihajar\Terbilang\Facades\Terbilang::make(300_000);
```

jika tidak bisa gunakan app injection. contoh :
```php
$terbilang = new Riskihajar\Terbilang\Terbilang;
$text = $terbilang->make(300_000);
```

**Comment by priana13** [comment]
oke Mas @riskihajar 

Terimakasih Mas.
