### ISSUE TITLE
Terbilang bahasa indonesianya masih salah. 

### ISSUE THREAD

**Issue by tarlusah** [riskihajar/terbilang#3]
1000000 -> satu juta bukan sejuta,

**Comment by riskihajar** [comment]
mohon maaf, update sebelumnya ada kesalahan logic, namun sudah diperbaiki https://github.com/riskihajar/terbilang/commit/251cd591d4d3bc6be923d51d1bdb7cc30fcb09a9
silakan `composer update` untuk update ke versi `1.0.4`

**Comment by tarlusah** [comment]
thanks udah di update mas.. :)
