### ISSUE TITLE
After dot doesn't check the number is zero or not

### ISSUE THREAD

**Issue by Ridarso** [riskihajar/terbilang#4]
add new rule validation on line 105:

if (null !== $fraction && is_numeric($fraction) && intval($fraction) > 0) {
....

**Comment by riskihajar** [comment]
Hi, @Ridarso this is helped?

https://github.com/riskihajar/terbilang/commit/ff2a3926a08b8366282d0f5417052d127548b4e0

**Comment by Ridarso** [comment]
yes, very helpful. Thanks
